// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public int JobId { get; set; }

    public int JobSeekerId { get; set; }

    public DateOnly AppliedDate { get; set; }

    public string Status { get; set; }

    public virtual JobPost Job { get; set; }

    public virtual JobApplicant JobSeeker { get; set; }
}