// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class Company
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string Type { get; set; }

    public string Website { get; set; }

    public string Location { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<JobPost> JobPosts { get; set; } = new List<JobPost>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}