// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class CompanyRegistration
{
    public int CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }
}