// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? CompanyId { get; set; }

    public int? UserId { get; set; }

    public string Message { get; set; }

    public string Status { get; set; }

    public virtual Company Company { get; set; }

    public virtual JobApplicant User { get; set; }
}