// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class PasswordReset
{
    public int ResetId { get; set; }

    public int UserId { get; set; }

    public string Username { get; set; }

    public byte[] Password { get; set; }

    public virtual ApplicantRegistration User { get; set; }
}