// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobServicePortal.Models;

public partial class SavedJob
{
    public int SavedJobId { get; set; }

    public int? UserId { get; set; }

    public int? JobId { get; set; }

    public DateTime? SavedAt { get; set; }

    public virtual JobPost Job { get; set; }

    public virtual JobApplicant User { get; set; }
}